Resources:
  Messages:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.messagesTableName}
      AttributeDefinitions:
        - AttributName: userID
          AttributeType: S
        - AttributeName: sentTime
          AttributeType: N
      KeySchema:
        - AttributeName: userID
          KeyType: HASH
        - AttributeName: sentTime
          KeyType: RANGE

      BillingMode: PAY_PER_REQUEST